name: Open Mayor
description: Using open-source to get politics out of city hall.
meta_description: "Using open-source to get politics out of city hall."

markdown: redcarpet
pygments: true
relative_permalinks: false

url:            'blog url'
author:         'Your Name'
